name: fixitnew

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.5.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  path_provider: ^2.1.2
  cloud_functions: ^6.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Montserrat font configuration
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
